version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
  mongodb:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "7017:27017"
    volumes:
      - db:/data/db
  backend:
    depends_on:
      - mongodb
    build: ./backend
    ports:
      - 8093:8093
    restart: always

volumes:
  db:
